# Shared RoPac paths — source from setup.sh / start.sh
# shellcheck disable=SC2034
ROPAC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export ROPAC_DIR

# Default: Ollama's standard models folder (~/.ollama/models).
DEFAULT_OLLAMA_MODELS="${HOME:-}/.ollama/models"
if [[ -d "$DEFAULT_OLLAMA_MODELS" ]]; then
  export OLLAMA_MODELS="$DEFAULT_OLLAMA_MODELS"
else
  export OLLAMA_MODELS="$ROPAC_DIR/ollama_models"
fi

export TTS_DIR="$ROPAC_DIR/data/tts"
export HF_HOME="$TTS_DIR/huggingface"
export HF_HUB_CACHE="$HF_HOME/hub"
export HUGGINGFACE_HUB_CACHE="$HF_HUB_CACHE"
export TRANSFORMERS_CACHE="$HF_HOME/transformers"
export TORCH_HOME="$TTS_DIR/torch"
mkdir -p "$OLLAMA_MODELS" "$ROPAC_DIR/data" "$TTS_DIR" "$HF_HOME/hub" "$TORCH_HOME"
# Do not populate ropac/ollama_models unless user opts into portable mode.

write_ropac_env_file() {
  cat >"$ROPAC_DIR/ropac.env" <<EOF
# Auto-generated by setup.sh — do not edit paths after moving the folder.
ROPAC_DIR=$ROPAC_DIR
OLLAMA_MODELS=$OLLAMA_MODELS
TTS_DIR=$TTS_DIR
HF_HOME=$HF_HOME
HF_HUB_CACHE=$HF_HUB_CACHE
TRANSFORMERS_CACHE=$TRANSFORMERS_CACHE
TORCH_HOME=$TORCH_HOME
# Cloud API keys are entered in the app at send time (not stored here).
EOF
}
